// Generated by scripts/generate-api-types.mjs. Do not edit.

export interface paths {
	'/api/v1/index': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Full registry index */
		get: operations['api_v1_index_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/featured': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Featured modules */
		get: operations['api_v1_featured_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List modules */
		get: operations['api_v1_modules_get'];
		put?: never;
		/** Create module */
		post: operations['api_v1_modules_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/mine': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List modules owned by the current user */
		get: operations['api_v1_modules_mine_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Search modules */
		get: operations['api_v1_modules_search_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get module by UUID */
		get: operations['api_v1_modules_uuid_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}/download': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Increment module downloads
		 * @description Legacy endpoint. When DOWNLOADS_MODE=logpush, download counts are derived from package log ingestion and this endpoint is a no-op.
		 */
		post: operations['api_v1_modules_uuid_download_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}/versions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List module versions */
		get: operations['api_v1_modules_uuid_versions_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}/versions/{version}/upload': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Upload module package */
		post: operations['api_v1_modules_uuid_versions_version_upload_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}/versions/{version}/publish': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Publish module version */
		post: operations['api_v1_modules_uuid_versions_version_publish_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}/related': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Related modules */
		get: operations['api_v1_modules_uuid_related_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}/reviews': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List module reviews */
		get: operations['api_v1_modules_uuid_reviews_get'];
		/** Update review */
		put: operations['api_v1_modules_uuid_reviews_put'];
		/** Create review */
		post: operations['api_v1_modules_uuid_reviews_post'];
		/** Delete review */
		delete: operations['api_v1_modules_uuid_reviews_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/categories': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List categories */
		get: operations['api_v1_categories_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/landing': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Landing page data */
		get: operations['api_v1_landing_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Verify GitHub auth token */
		get: operations['api_v1_auth_verify_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/sync': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sync authenticated user */
		post: operations['api_v1_auth_sync_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Current user profile */
		get: operations['api_v1_users_me_get'];
		put?: never;
		post?: never;
		/** Delete current user account */
		delete: operations['api_v1_users_me_delete'];
		options?: never;
		head?: never;
		/** Update current user profile */
		patch: operations['api_v1_users_me_patch'];
		trace?: never;
	};
	'/api/v1/users/{username}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Public user profile */
		get: operations['api_v1_users_username_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/{username}/modules': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Modules by user */
		get: operations['api_v1_users_username_modules_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/collections': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List current user collections */
		get: operations['api_v1_collections_get'];
		put?: never;
		/** Create collection */
		post: operations['api_v1_collections_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/collections/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get collection detail */
		get: operations['api_v1_collections_id_get'];
		put?: never;
		post?: never;
		/** Delete collection */
		delete: operations['api_v1_collections_id_delete'];
		options?: never;
		head?: never;
		/** Update collection */
		patch: operations['api_v1_collections_id_patch'];
		trace?: never;
	};
	'/api/v1/collections/{id}/modules': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Add module to collection */
		post: operations['api_v1_collections_id_modules_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/collections/{id}/modules/{uuid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Remove module from collection */
		delete: operations['api_v1_collections_id_modules_uuid_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/{username}/collections': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Public collections by user */
		get: operations['api_v1_users_username_collections_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}/screenshots': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List module screenshots */
		get: operations['api_v1_modules_uuid_screenshots_get'];
		put?: never;
		/** Upload module screenshot */
		post: operations['api_v1_modules_uuid_screenshots_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}/screenshots/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete module screenshot */
		delete: operations['api_v1_modules_uuid_screenshots_id_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/screenshots/{uuid}/{filename}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Serve module screenshot */
		get: operations['screenshots_uuid_filename_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/users/me/stars': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Current user stars */
		get: operations['api_v1_users_me_stars_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/stars/sync': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sync stars */
		post: operations['api_v1_stars_sync_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/modules/{uuid}/star': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Star status */
		get: operations['api_v1_modules_uuid_star_get'];
		put?: never;
		/** Star module */
		post: operations['api_v1_modules_uuid_star_post'];
		/** Unstar module */
		delete: operations['api_v1_modules_uuid_star_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/notifications': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List notifications */
		get: operations['api_v1_notifications_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/notifications/unread-count': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Notification unread count */
		get: operations['api_v1_notifications_unread_count_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/notifications/{id}/read': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Mark notification read */
		patch: operations['api_v1_notifications_id_read_patch'];
		trace?: never;
	};
	'/api/v1/notifications/mark-all-read': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Mark all notifications read */
		post: operations['api_v1_notifications_mark_all_read_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/notifications/preferences': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get notification preferences */
		get: operations['api_v1_notifications_preferences_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update notification preferences */
		patch: operations['api_v1_notifications_preferences_patch'];
		trace?: never;
	};
	'/api/v1/notifications/stream': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Stream notifications (SSE) */
		get: operations['api_v1_notifications_stream_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/notifications/announcements': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Broadcast announcement */
		post: operations['api_v1_notifications_announcements_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/security/check': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Security check */
		get: operations['security_check_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/packages/{uuid}/{version}/{filename}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Download module package */
		get: operations['packages_uuid_version_filename_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/submissions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List pending submissions */
		get: operations['api_v1_admin_submissions_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/submissions/{id}/approve': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Approve submission */
		post: operations['api_v1_admin_submissions_id_approve_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/submissions/{id}/reject': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Reject submission */
		post: operations['api_v1_admin_submissions_id_reject_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/users/{id}/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Toggle verified author */
		post: operations['api_v1_admin_users_id_verify_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/stats': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Admin stats */
		get: operations['api_v1_admin_stats_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health check */
		get: operations['api_v1_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ApiVersion: {
			/** @example 1 */
			version: number;
		};
		/** @description RFC 9457 Problem Details error response. */
		ProblemDetails: {
			/**
			 * Format: uri-reference
			 * @description Problem type URI; about:blank indicates no extra semantics beyond the HTTP status.
			 * @default about:blank
			 */
			type: string;
			title: string;
			status: number;
			detail: string;
			/** Format: uri-reference */
			instance?: string;
			/** @description Stable, application-level error code. */
			code?: string;
			/** @description Opaque identifier for correlating errors in logs. */
			error_id?: string;
		};
		/**
		 * @description Semantic version string.
		 * @example 1.2.0
		 */
		ModuleVersion: string;
		/** @enum {string} */
		ModuleCategory:
			| 'system'
			| 'hardware'
			| 'network'
			| 'audio'
			| 'power'
			| 'time'
			| 'workspace'
			| 'window'
			| 'tray'
			| 'weather'
			| 'productivity'
			| 'media'
			| 'custom';
		CategoryInfo: {
			id?: string | null;
			name: string;
			icon: string;
		};
		/**
		 * Format: uri
		 * @description HTTPS repository URL.
		 */
		RepoUrl: string;
		RegistryModule: {
			/** @example weather-wttr@barforge */
			uuid: string;
			name: string;
			description: string;
			author: string;
			category: components['schemas']['ModuleCategory'];
			icon?: string | null;
			screenshot?: string | null;
			repo_url: components['schemas']['RepoUrl'];
			/** Format: int64 */
			downloads: number;
			version?: components['schemas']['ModuleVersion'] | null;
			/** Format: date-time */
			last_updated?: string | null;
			/** Format: float */
			rating?: number | null;
			verified_author: boolean;
			tags: string[];
			checksum?: string | null;
			license?: string | null;
		};
		RegistryIndex: {
			version: number;
			modules: components['schemas']['RegistryModule'][];
			categories: {
				[key: string]: components['schemas']['CategoryInfo'];
			};
		};
		ModulesResponse: {
			modules: components['schemas']['RegistryModule'][];
			total: number;
		};
		CategoriesResponse: {
			categories: components['schemas']['CategoryInfo'][];
		};
		ReviewUser: {
			username: string;
			avatar_url?: string | null;
		};
		Review: {
			/** Format: int64 */
			id: number;
			rating: number;
			title?: string | null;
			body?: string | null;
			/** Format: int64 */
			helpful_count: number;
			user: components['schemas']['ReviewUser'];
			created_at: string;
			updated_at?: string | null;
		};
		ReviewsResponse: {
			reviews: components['schemas']['Review'][];
			total: number;
		};
		VersionHistoryEntry: {
			version: string;
			changelog?: string | null;
			/** Format: int64 */
			downloads: number;
			published_at: string;
		};
		VersionsResponse: {
			versions: components['schemas']['VersionHistoryEntry'][];
			total: number;
		};
		/** @enum {string} */
		UserRole: 'user' | 'moderator' | 'admin';
		UserProfile: {
			/** Format: int64 */
			id: number;
			username: string;
			display_name?: string | null;
			avatar_url?: string | null;
			bio?: string | null;
			website_url?: string | null;
			github_url?: string | null;
			twitter_url?: string | null;
			bluesky_url?: string | null;
			discord_url?: string | null;
			sponsor_url?: string | null;
			verified_author: boolean;
			role: components['schemas']['UserRole'];
			/** Format: int64 */
			module_count: number;
			created_at: string;
		};
		DeleteAccountResponse: {
			message: string;
		};
		AuthVerifyResponse: {
			authenticated: boolean;
			/** Format: int64 */
			github_id?: number | null;
			github_login?: string | null;
			user_in_db?: boolean | null;
			/** Format: int64 */
			db_user_id?: number | null;
			reason?: string | null;
		};
		AuthSyncResponse: {
			/** Format: int64 */
			user_id: number;
			username: string;
		};
		AnnouncementRequest: {
			title: string;
			body: string;
			action_url?: string | null;
		};
		AnnouncementResponse: {
			sent: number;
		};
		PublicStats: {
			/** Format: int64 */
			total_modules: number;
			/** Format: int64 */
			total_downloads: number;
			/** Format: int64 */
			total_authors: number;
		};
		LandingInstallMethod: {
			id: string;
			label: string;
			description: string;
			commands: string[];
		};
		LandingData: {
			stats: components['schemas']['PublicStats'];
			install_methods: components['schemas']['LandingInstallMethod'][];
		};
		FeaturedResponse: {
			featured: components['schemas']['RegistryModule'][];
			popular: components['schemas']['RegistryModule'][];
			recent: components['schemas']['RegistryModule'][];
		};
		CollectionOwner: {
			username: string;
			display_name?: string | null;
			avatar_url?: string | null;
		};
		Collection: {
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			user_id: number;
			name: string;
			description?: string | null;
			visibility: string;
			/** Format: int64 */
			module_count: number;
			owner: components['schemas']['CollectionOwner'];
			created_at: string;
			updated_at: string;
		};
		CollectionModule: {
			uuid: string;
			name: string;
			author: string;
			category: string;
			note?: string | null;
			position: number;
			added_at: string;
		};
		CollectionsResponse: {
			collections: components['schemas']['Collection'][];
			total: number;
		};
		CollectionDetailResponse: {
			collection: components['schemas']['Collection'];
			modules: components['schemas']['CollectionModule'][];
		};
		CollectionCreateResponse: {
			/** Format: int64 */
			id: number;
			message: string;
		};
		Screenshot: {
			/** Format: int64 */
			id: number;
			r2_key: string;
			alt_text?: string | null;
			position: number;
			created_at: string;
		};
		ScreenshotsResponse: {
			screenshots: components['schemas']['Screenshot'][];
			total: number;
		};
		ScreenshotUploadData: {
			/** Format: int64 */
			id: number;
			r2_key: string;
			url: string;
		};
		ScreenshotUploadResponse: {
			version: number;
			data: components['schemas']['ScreenshotUploadData'];
		};
		ScreenshotDeleteResponse: {
			version: number;
			data: {
				deleted: boolean;
			};
		};
		StarredModule: components['schemas']['RegistryModule'] & {
			starred_at: string;
		};
		StarsResponse: {
			modules: components['schemas']['StarredModule'][];
			total: number;
		};
		StarStatusResponse: {
			starred: boolean;
			/** Format: int64 */
			star_count: number;
		};
		SyncStarsRequest: {
			uuids: string[];
			is_public?: boolean;
		};
		SyncStarsResponse: {
			synced: number;
		};
		Notification: {
			/** Format: int64 */
			id: number;
			/** @enum {string} */
			notification_type: 'downloads' | 'comments' | 'stars' | 'updates' | 'announcements';
			title: string;
			body?: string | null;
			action_url?: string | null;
			is_read: boolean;
			created_at: string;
		};
		NotificationPreferences: {
			downloads_enabled: boolean;
			comments_enabled: boolean;
			stars_enabled: boolean;
			updates_enabled: boolean;
			announcements_enabled: boolean;
			email_downloads: boolean;
			email_comments: boolean;
			email_stars: boolean;
			email_updates: boolean;
			email_announcements: boolean;
		};
		NotificationsResponse: {
			notifications: components['schemas']['Notification'][];
			total: number;
		};
		UnreadCountResponse: {
			/** Format: int64 */
			unread_count: number;
		};
		MarkReadResponse: {
			success: boolean;
		};
		MarkAllReadResponse: {
			/** Format: int64 */
			marked_count: number;
		};
		CreateModuleRequest: {
			uuid: string;
			name: string;
			description: string;
			category: string;
			repo_url: components['schemas']['RepoUrl'];
			license: string;
		};
		CreateModuleResponse: {
			uuid: string;
			message: string;
		};
		UploadResponse: {
			uuid: string;
			version: string;
			r2_key: string;
			message: string;
		};
		PublishRequest: {
			changelog?: string | null;
		};
		PublishResponse: {
			uuid: string;
			version: string;
			message: string;
		};
		CreateReviewRequest: {
			rating: number;
			title?: string | null;
			body?: string | null;
		};
		UpdateProfileRequest: {
			display_name?: string | null;
			bio?: string | null;
			website_url?: string | null;
			github_url?: string | null;
			twitter_url?: string | null;
			bluesky_url?: string | null;
			discord_url?: string | null;
			sponsor_url?: string | null;
		};
		CreateCollectionRequest: {
			name: string;
			description?: string | null;
			visibility?: ('private' | 'public' | 'unlisted') | null;
		};
		UpdateCollectionRequest: {
			name?: string | null;
			description?: string | null;
			visibility?: ('private' | 'public' | 'unlisted') | null;
		};
		AddModuleRequest: {
			module_uuid: string;
			note?: string | null;
		};
		StarRequest: {
			is_public?: boolean | null;
		};
		VerifyResponse: {
			/** Format: int64 */
			user_id: number;
			verified_author: boolean;
		};
		AdminStats: {
			/** Format: int64 */
			total_modules: number;
			/** Format: int64 */
			total_users: number;
			/** Format: int64 */
			total_downloads: number;
			/** Format: int64 */
			pending_submissions: number;
		};
		Submission: {
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			submitter_id: number;
			uuid: string;
			name: string;
			description: string;
			category: string;
			version: string;
			repo_url: components['schemas']['RepoUrl'];
			status: string;
			rejection_reason?: string | null;
			submitted_at: string;
			reviewed_at?: string | null;
			/** Format: int64 */
			reviewed_by?: number | null;
			submitter_username: string;
		};
		SubmissionsResponse: {
			submissions: components['schemas']['Submission'][];
			total: number;
		};
		RejectRequest: {
			reason: string;
		};
	};
	responses: {
		/** @description Bad request. */
		BadRequest: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/problem+json': components['schemas']['ProblemDetails'];
			};
		};
		/** @description Authentication required. */
		Unauthorized: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/problem+json': components['schemas']['ProblemDetails'];
			};
		};
		/** @description Access denied. */
		Forbidden: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/problem+json': components['schemas']['ProblemDetails'];
			};
		};
		/** @description Resource not found. */
		NotFound: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/problem+json': components['schemas']['ProblemDetails'];
			};
		};
		/** @description Conflict. */
		Conflict: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/problem+json': components['schemas']['ProblemDetails'];
			};
		};
		/** @description Content-Length header required. */
		LengthRequired: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/problem+json': components['schemas']['ProblemDetails'];
			};
		};
		/** @description Payload too large. */
		PayloadTooLarge: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/problem+json': components['schemas']['ProblemDetails'];
			};
		};
		/** @description Too many requests. */
		RateLimited: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/problem+json': components['schemas']['ProblemDetails'];
			};
		};
		/** @description Internal server error. */
		InternalError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/problem+json': components['schemas']['ProblemDetails'];
			};
		};
	};
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	api_v1_index_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Registry index */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RegistryIndex'];
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_featured_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Featured modules */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['FeaturedResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_get: {
		parameters: {
			query?: {
				q?: string;
				category?: string;
				sort?: string;
				limit?: number;
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Module list */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['ModulesResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateModuleRequest'];
			};
		};
		responses: {
			/** @description Module created */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['CreateModuleResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_mine_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User modules */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['ModulesResponse'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_search_get: {
		parameters: {
			query?: {
				q?: string;
				category?: string;
				sort?: string;
				limit?: number;
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Search results */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['ModulesResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Module */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['RegistryModule'];
				};
			};
			400: components['responses']['BadRequest'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_download_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Download counted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_versions_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Version history */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['VersionsResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_versions_version_upload_post: {
		parameters: {
			query?: never;
			header: {
				/** @description Size of the upload in bytes (max 104857600). */
				'Content-Length': number;
			};
			path: {
				uuid: string;
				version: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/gzip': string;
				'application/octet-stream': string;
			};
		};
		responses: {
			/** @description Upload response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['UploadResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			411: components['responses']['LengthRequired'];
			413: components['responses']['PayloadTooLarge'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_versions_version_publish_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
				version: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['PublishRequest'];
			};
		};
		responses: {
			/** @description Publish response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['PublishResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			409: components['responses']['Conflict'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_related_get: {
		parameters: {
			query?: {
				limit?: number;
			};
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Related modules */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['ModulesResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_reviews_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Reviews */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['ReviewsResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_reviews_put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateReviewRequest'];
			};
		};
		responses: {
			/** @description Review updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_reviews_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateReviewRequest'];
			};
		};
		responses: {
			/** @description Review created */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			409: components['responses']['Conflict'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_reviews_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Review deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_categories_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Categories */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['CategoriesResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_landing_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Landing data */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['LandingData'];
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_auth_verify_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Auth verify response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthVerifyResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_auth_sync_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Auth sync response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['AuthSyncResponse'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_users_me_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User profile */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['UserProfile'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_users_me_delete: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Account deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['DeleteAccountResponse'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_users_me_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateProfileRequest'];
			};
		};
		responses: {
			/** @description Profile updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_users_username_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				username: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User profile */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['UserProfile'];
				};
			};
			400: components['responses']['BadRequest'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_users_username_modules_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				username: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User modules */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['ModulesResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_collections_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Collections */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['CollectionsResponse'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_collections_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateCollectionRequest'];
			};
		};
		responses: {
			/** @description Collection created */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['CollectionCreateResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_collections_id_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Collection detail */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['CollectionDetailResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_collections_id_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Collection deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_collections_id_patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateCollectionRequest'];
			};
		};
		responses: {
			/** @description Collection updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_collections_id_modules_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AddModuleRequest'];
			};
		};
		responses: {
			/** @description Module added */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_collections_id_modules_uuid_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Module removed */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_users_username_collections_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				username: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Collections */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['CollectionsResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_screenshots_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Screenshots */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['ScreenshotsResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_screenshots_post: {
		parameters: {
			query?: {
				alt_text?: string;
			};
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'image/png': string;
				'image/jpeg': string;
				'image/webp': string;
			};
		};
		responses: {
			/** @description Screenshot uploaded */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScreenshotUploadResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			413: components['responses']['PayloadTooLarge'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_screenshots_id_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Screenshot deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScreenshotDeleteResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	screenshots_uuid_filename_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
				filename: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Screenshot bytes */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'image/png': string;
					'image/jpeg': string;
					'image/webp': string;
					'application/octet-stream': string;
				};
			};
			400: components['responses']['BadRequest'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_users_me_stars_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Starred modules */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['StarsResponse'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_stars_sync_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SyncStarsRequest'];
			};
		};
		responses: {
			/** @description Sync result */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['SyncStarsResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_star_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Star status */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['StarStatusResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_star_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				'application/json': components['schemas']['StarRequest'];
			};
		};
		responses: {
			/** @description Starred */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_modules_uuid_star_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Unstarred */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_notifications_get: {
		parameters: {
			query?: {
				limit?: number;
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Notifications */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['NotificationsResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_notifications_unread_count_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Unread count */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['UnreadCountResponse'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_notifications_id_read_patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Mark read */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['MarkReadResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_notifications_mark_all_read_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Mark all read */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['MarkAllReadResponse'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_notifications_preferences_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Preferences */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['NotificationPreferences'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_notifications_preferences_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['NotificationPreferences'];
			};
		};
		responses: {
			/** @description Preferences updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['NotificationPreferences'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_notifications_stream_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Notification event stream */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/event-stream': string;
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_notifications_announcements_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AnnouncementRequest'];
			};
		};
		responses: {
			/** @description Announcement dispatched */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['AnnouncementResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			429: components['responses']['RateLimited'];
			500: components['responses']['InternalError'];
		};
	};
	security_check_get: {
		parameters: {
			query: {
				uuid: string;
				version: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Security check response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						uuid: string;
						version: string;
						revoked: boolean;
						reason?: string | null;
					};
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
	packages_uuid_version_filename_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uuid: string;
				version: string;
				filename: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Package bytes */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/gzip': string;
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_admin_submissions_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Pending submissions */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['SubmissionsResponse'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_admin_submissions_id_approve_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Submission approved */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_admin_submissions_id_reject_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RejectRequest'];
			};
		};
		responses: {
			/** @description Submission rejected */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_admin_users_id_verify_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Verification updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['VerifyResponse'];
				};
			};
			400: components['responses']['BadRequest'];
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_admin_stats_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Admin stats */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiVersion'] &
						components['schemas']['AdminStats'];
				};
			};
			401: components['responses']['Unauthorized'];
			403: components['responses']['Forbidden'];
			500: components['responses']['InternalError'];
		};
	};
	api_v1_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			400: components['responses']['BadRequest'];
			500: components['responses']['InternalError'];
		};
	};
}
